### ISSUE TITLE
抓取报错

### ISSUE THREAD

**Issue by noood** [zhengxiaotian/geek_crawler#19]
大神来看下呀：

/Users/bo/PycharmProjects/pythonProject/main.py[line:550] - ERROR: 请求过程中出错了，出错信息为：Traceback (most recent call last):
  File "/Users/bo/PycharmProjects/pythonProject/main.py", line 547, in <module>
    run(cellphone, pwd, exclude=exclude, get_comments=get_comments)
  File "/Users/bo/PycharmProjects/pythonProject/main.py", line 513, in run
    geek._article(aid, pro, file_type=file_type, get_comments=get_comments)  # 获取单个文章的信息
  File "/Users/bo/PycharmProjects/pythonProject/main.py", line 341, in _article
    self.save_to_file(
  File "/Users/bo/PycharmProjects/pythonProject/main.py", line 449, in save_to_file
    os.mkdir(dir_path)
FileNotFoundError: [Errno 2] No such file or directory: 'A/B测试从0到1'

**Comment by MIDE-589** [comment]
专栏名中有非法字符，所以无法创建目录。
我简单看了眼，作者写了一个check_filename函数用来过滤文件名中的斜杠，但没过滤目录名。
所以，在第446行下面加一句：
        dir_name = check_filename(dir_name)
亲测可用
